Repository SpareBank1/designsystem, pull requests merged in 2018-03, with the labels that each got.

#42 ffe-account-selector-react: Disregard formatting when searching for account numbers
  packages/ffe-account-selector-react/src/components/account-selector/AccountSelector.md
  packages/ffe-account-selector-react/src/filter/filters.js
  packages/ffe-account-selector-react/src/filter/filters.spec.js
Labels: :gem: enhancement

#45 ffe-form: Add vertical padding to ffe-textarea
  packages/ffe-form-react/src/TextArea.md
  packages/ffe-form/less/textarea.less
Labels: :bug: bug

#63 infra: Add coverage reporting to CI build (#7)
  .gitignore
  .travis.yml
  package.json
Labels: :computer: technical

#71 docs: Reduce to one blank line between list items
  styleguide-content/merkevare/stil-og-tone.md
Labels: :bug: bug, :dizzy: design system

#65 Improve experience when going to Komponenter
  package.json
  src/styles/styles.less
  src/templates/frontpage.hbs
  src/templates/page.hbs
  src/templates/styleguidist.hbs
  styleguide.config.js
Labels: :bug: bug, :dizzy: design system

#75 fix: Limit to 2 concurrent tasks when linting
  package.json
Labels: :computer: technical

#78 infra: Set up deploy to gh-pages
  .travis.yml
Labels: :computer: technical

#111 Fix a typo in a chart-donut media query
  packages/ffe-chart-donut-react/src/ffe-chart-donut.less
Labels: :bug: bug, :rocket: ffe
